config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs, :controllers => { :registrations => 'registrations' }
  # root 'welcome#index'

  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  #resources :recipes
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe' 
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"  
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
  get '/chapter1_1', to: 'chapters#chapter1_1'
  get '/chapter1_2', to: 'chapters#chapter1_2'
  get '/chapter1_3', to: 'chapters#chapter1_3'
  get '/chapter1_4', to: 'chapters#chapter1_4'
  
  get '/chapter2_1', to: 'chapters#chapter2_1'
  get '/chapter2_2', to: 'chapters#chapter2_2'
  get '/chapter2_3', to: 'chapters#chapter2_3'
  
  get '/chapter3_1', to: 'chapters#chapter3_1'
  get '/chapter3_2', to: 'chapters#chapter3_2'
  
  get '/chapter4_1', to: 'chapters#chapter4_1'
  get '/chapter4_2', to: 'chapters#chapter4_2'
  get '/chapter4_3', to: 'chapters#chapter4_3'
  get '/chapter4_4', to: 'chapters#chapter4_4'
  get '/chapter4_5', to: 'chapters#chapter4_5'
  
  get '/chapter5_1', to: 'chapters#chapter5_1'
  get '/chapter5_2', to: 'chapters#chapter5_2'
  
  get '/chapter6_1', to: 'chapters#chapter6_1'
  get '/chapter6_2', to: 'chapters#chapter6_2'
  
  get '/chapter7_1', to: 'chapters#chapter7_1'
  get '/chapter7_2', to: 'chapters#chapter7_2'
  get '/chapter7_3', to: 'chapters#chapter7_3'
  
  get '/chapter8_1', to: 'chapters#chapter8_1'
  get '/chapter8_2', to: 'chapters#chapter8_2'
  
  get '/chapter9_1', to: 'chapters#chapter9_1'
  get '/chapter9_2', to: 'chapters#chapter9_2'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if current_chef %>
  <h3>Welcome: <%= current_chef.email %></h3>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      You'll love managing your Photos with our application. Sign up!
    </p>
  </div>

  <div class="row">
    <div class="plans clearfix">
      <div class="col-lg-3 col-lg-offset-3 plan">
        <h2>Premium Plan</h2>
        <div class="price pull-right">
          Price: $10
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_chef_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
      <div class="col-lg-3 plan">
        <h2>Amaze Plan</h2>
        <div class="price pull-right">
          Price: $20
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
            <li class='extra'>Unlimited projects</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_chef_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
    </div>
  </div>
<% end %>