config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs, :controllers => { :registrations => 'registrations' }
  # root 'welcome#index'

  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  #resources :recipes
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe' 
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"  
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
  get '/chapter1_1', to: 'chapters#chapter1_1'
  get '/chapter1_2', to: 'chapters#chapter1_2'
  get '/chapter1_3', to: 'chapters#chapter1_3'
  get '/chapter1_4', to: 'chapters#chapter1_4'
  
  get '/chapter2_1', to: 'chapters#chapter2_1'
  get '/chapter2_2', to: 'chapters#chapter2_2'
  get '/chapter2_3', to: 'chapters#chapter2_3'
  
  get '/chapter3_1', to: 'chapters#chapter3_1'
  get '/chapter3_2', to: 'chapters#chapter3_2'
  
  get '/chapter4_1', to: 'chapters#chapter4_1'
  get '/chapter4_2', to: 'chapters#chapter4_2'
  get '/chapter4_3', to: 'chapters#chapter4_3'
  get '/chapter4_4', to: 'chapters#chapter4_4'
  get '/chapter4_5', to: 'chapters#chapter4_5'
  
  get '/chapter5_1', to: 'chapters#chapter5_1'
  get '/chapter5_2', to: 'chapters#chapter5_2'
  
  get '/chapter6_1', to: 'chapters#chapter6_1'
  get '/chapter6_2', to: 'chapters#chapter6_2'
  
  get '/chapter7_1', to: 'chapters#chapter7_1'
  get '/chapter7_2', to: 'chapters#chapter7_2'
  get '/chapter7_3', to: 'chapters#chapter7_3'
  
  get '/chapter8_1', to: 'chapters#chapter8_1'
  get '/chapter8_2', to: 'chapters#chapter8_2'
  
  get '/chapter9_1', to: 'chapters#chapter9_1'
  get '/chapter9_2', to: 'chapters#chapter9_2'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
    Copyright &copy; 2017 Mike Dalton; All Rights Reserved.
  
  <nav>
    <ul>
      <li><%#= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
      data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" 
                                                aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Main", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
<!-- ================= start chapte list =============================== -->         
       <!--<li class="dropdown">-->
       <!--   <a href="#" class="dropdown-toggle" data-toggle="dropdown" -->
       <!--   role="button" aria-haspopup="true" aria-expanded="false">-->
       <!--   Menu-->
       <!--   <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
          <!--  <li><#%= link_to "Introduction", chapter1_1_path %></li>-->
          <!--  <li><#%= link_to "Variables", chapter2_1_path %></li>-->
          <!--  <li><#%= link_to "Conditional Statements", chapter3_1_path %></li>-->
          <!--  <li><#%= link_to "Best Programming Practices", chapter4_1_path %></li>-->
          <!--  <li><#%= link_to "While Loops", chapter5_1_path %></li>-->
          <!--  <li><#%= link_to "For Loops", chapter6_1_path %></li>-->
          <!--  <li><#%= link_to "Arrays", chapter7_1_path %></li>-->
          <!--  <li><#%= link_to "Methods", chapter8_1_path %></li>-->
          <!--  <li><#%= link_to "Strings", chapter9_1_path %></li>-->
          <!--</ul>-->
<!-- =================== End chapte list =============================== -->        
        <li><%= link_to "All Posts", recipes_path %></li>
        <!--<#% if logged_in? %>-->
          <li><%= link_to "New Posts", new_recipe_path %></li>
          <li><%= link_to "Chat", chat_path %></li>
        <!--<#% end %>-->
        <!-- =============== display all user ================= -->
        <!--<#% if logged_in? && current_chef.admin? %>-->
           <li><%= link_to "User", chefs_path %></li>
        <!--<#% end %>-->
        <!-- ================================================== -->        
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <!--Add-->
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <!--end add-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.capitalize %>'s Profile 
                                <%= "Admin" if current_chef.admin? %> 
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", 
                                chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile", 
                                edit_chef_path(current_chef) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, 
                                      method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up user", new_chef_registration_path %></li>
          <li><%= link_to "Log Out user", destroy_chef_session_path, method: :delete %></li>        
          <li><%= link_to "Log In", login_path %></li>          
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!--copy-->
        <!--these below only work with old login-->
        <!--<#% if chef_signed_in? %>-->
        <!--  <li><#%= link_to "Testing chef_signed_in", new_chef_registration_path %></li><li>-->
        <!--<#% end%>-->
        <!--<#% if current_chef %>-->
        <!--  <li><#%= link_to "Testing current_chef", new_chef_registration_path %></li><li>-->
        <!--<#% end %>-->

          <!--<li><#%= link_to "Sign Up", new_chef_registration_path %></li>-->
          <!--<li><#%= link_to "Log In", login_path %></li>  -->
          <!--<li><#%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>-->
        
 <!--<li><#%= link_to "Sign In user", new_chef_session_path %>-->   
  <!--<li><#%= link_to "Log out chef", logout_path, method: :delete %></li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Java Tutorial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <br/><br/>
    <%= render 'layouts/messages' %>
    
    <div id="bg">
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    </div>
  </body>
</html>